import {
  AbsoluteFill,
  Sequence,
  Series,
  staticFile,
  useCurrentFrame,
  useVideoConfig,
  Video,
} from "remotion";
import { Audio } from "@remotion/media";
import { z } from "zod";
import videoData from "../../public/content/AivsSWE/video.json";
import { WowBackground } from "../shorts/codeorcap/scenes/WowBackground";
import { HookScene } from "../shorts/codeorcap/scenes/HookScene";
import { ClaimScene } from "../shorts/codeorcap/scenes/ClaimScene";
import { GroundRulesScene } from "../shorts/codeorcap/scenes/GroundRulesScene";
import { SWEDataScene } from "../shorts/codeorcap/scenes/SWEDataScene";
import { AIDataScene } from "../shorts/codeorcap/scenes/AIDataScene";
import { HeadToHeadScene } from "../shorts/codeorcap/scenes/HeadToHeadScene";
import { RealityCheckScene } from "../shorts/codeorcap/scenes/RealityCheckScene";
import { VerdictScene5Min } from "./scenes/VerdictScene5Min";
import { CTAScene } from "../shorts/codeorcap/scenes/CTAScene";
import introVideo from "./intro.mp4";
import outroVideo from "./outro.mp4";
import { Img } from "remotion";
import logoImg from "./logo.png";

const SceneComponents = [
  HookScene,
  ClaimScene,
  GroundRulesScene,
  SWEDataScene,
  AIDataScene,
  HeadToHeadScene,
  RealityCheckScene,
  VerdictScene5Min,
  CTAScene,
];

const ProfessionalHUD: React.FC<{ previewMode: boolean }> = ({
  previewMode,
}) => {
  const frame = useCurrentFrame();
  const { fps } = useVideoConfig();

  const progress = frame / videoData.totalFrames;
  const timeSeconds = frame / fps;
  const timeString = `${Math.floor(timeSeconds / 60)}:${Math.floor(
    timeSeconds % 60,
  )
    .toString()
    .padStart(2, "0")}:${Math.floor((timeSeconds % 1) * 100)
    .toString()
    .padStart(2, "0")}`;

  // Find current scene
  let currentSceneIndex = 0;
  for (let i = 0; i < videoData.scenes.length; i++) {
    const scene = videoData.scenes[i];
    if (
      frame >= scene.startFrame &&
      frame < scene.startFrame + scene.durationFrames
    ) {
      currentSceneIndex = i;
      break;
    }
  }

  return (
    <AbsoluteFill style={{ pointerEvents: "none" }}>
      {/* Top Left: Scene Badge */}
      <div
        style={{
          position: "absolute",
          top: 60,
          left: 60,
          background: previewMode
            ? "rgba(30, 30, 30, 0.9)"
            : "rgba(255, 255, 255, 0.05)",
          backdropFilter: previewMode ? "none" : "blur(20px)",
          padding: "16px 32px",
          borderRadius: "100px",
          border: "1px solid rgba(255, 255, 255, 0.1)",
          boxShadow: previewMode ? "none" : "0 8px 32px rgba(0, 0, 0, 0.2)",
          display: "flex",
          alignItems: "center",
          gap: 16,
        }}
      >
        <div
          style={{
            width: 12,
            height: 12,
            borderRadius: "50%",
            background: "#10B981",
            boxShadow: previewMode ? "none" : "0 0 10px #10B981",
          }}
        />
        <span
          style={{
            color: "white",
            fontSize: 24,
            fontWeight: 600,
            fontFamily: "system-ui",
            letterSpacing: "0.1em",
          }}
        >
          SCENE {currentSceneIndex + 1} / {videoData.scenes.length}
        </span>
      </div>

      {/* Top Right: Timecode */}
      <div
        style={{
          position: "absolute",
          top: 60,
          right: 60,
          color: "rgba(255, 255, 255, 0.5)",
          fontSize: 28,
          fontFamily: "monospace",
          fontWeight: 500,
        }}
      >
        {timeString}
      </div>

      {/* Bottom: Neon Progress Bar */}
      <div
        style={{
          position: "absolute",
          bottom: 0,
          left: 0,
          right: 0,
          height: 8,
          background: "rgba(255, 255, 255, 0.1)",
        }}
      >
        <div
          style={{
            width: `${progress * 100}%`,
            height: "100%",
            background: "linear-gradient(90deg, #3B82F6, #8B5CF6, #EC4899)",
            boxShadow: previewMode
              ? "none"
              : "0 0 20px rgba(139, 92, 246, 0.8)",
          }}
        />
      </div>
    </AbsoluteFill>
  );
};

const sceneVideoMap: Record<string, string> = {
  hook: "01-tech.mp4",
  claim: "02-business.mp4",
  rules: "03-minimalist.mp4",
  swe: "02-business.mp4",
  ai: "01-tech.mp4",
  headToHead: "04-energetic.mp4",
  reality: "05-data.mp4",
  verdict: "06-luxury.mp4",
  cta: "06-luxury.mp4",
};

const MainContent: React.FC<{
  previewMode: boolean;
  logoOverlay: React.ReactNode;
}> = ({ previewMode, logoOverlay }) => {
  return (
    <AbsoluteFill style={{ backgroundColor: "#06080D" }}>
      {/* Wow-level background */}
      <WowBackground />
      {/* Main perfectly-synced voiceover track generated by scripts */}
      <Audio
        src={staticFile("content/AivsSWE/audio/voiceover.mp3")}
        volume={0.9}
      />
      {/* Ambient background drone */}
      <Audio
        src={staticFile("audio/background-music.mp3")}
        volume={0.15}
        loop
      />
      {videoData.scenes.map((scene: any, index: number) => {
        const SceneComponent = SceneComponents[index];
        if (!SceneComponent) return null;

        const bgVideo = sceneVideoMap[scene.id];

        return (
          <Sequence
            key={scene.id}
            from={scene.startFrame}
            durationInFrames={scene.durationFrames}
            style={{
              scale: 0.999,
              translate: "19.9px 77.2px",
            }}
          >
            {/* Background Video Layer */}
            {bgVideo && (
              <AbsoluteFill style={{ zIndex: 0 }}>
                <Video
                  src={staticFile(`content/AivsSWE/video/${bgVideo}`)}
                  style={{
                    width: "100%",
                    height: "100%",
                    objectFit: "cover",
                    opacity: 0.4,
                  }}
                  muted={false}
                  volume={0.2}
                  playbackRate={10 / scene.duration}
                  endAt={scene.durationFrames}
                  onError={(e) => console.log("Video error:", e)}
                />
              </AbsoluteFill>
            )}
            {/* Logo Overlay (behind text, on top of bg video) */}
            <AbsoluteFill style={{ zIndex: 1 }}>{logoOverlay}</AbsoluteFill>
            {/* Added a container for consistent Glassmorphism presentation, though components handle their own layout */}
            <AbsoluteFill
              style={{
                zIndex: 2,
                display: "flex",
                justifyContent: "center",
                alignItems: "center",
              }}
            >
              <SceneComponent />
            </AbsoluteFill>
          </Sequence>
        );
      })}
      {/* Professional HUD overlays everything */}
      <ProfessionalHUD previewMode={previewMode} />
    </AbsoluteFill>
  );
};

export const aiVsSWESchema = z.object({
  logoBottom: z.number().min(0).max(1080).step(1),
  logoRight: z.number().min(0).max(1920).step(1),
  logoScale: z.number().min(0.1).max(5).step(0.1),
  logoOpacity: z.number().min(0).max(1).step(0.05),
  blurAmount: z.number().min(0).max(50).step(1),
  logoBackgroundTransparency: z.number().min(0).max(1).step(0.05),
  previewMode: z.boolean(),
});

export type AIVsSWEProps = z.infer<typeof aiVsSWESchema>;

export const AIvsSWEVideo: React.FC<AIVsSWEProps> = ({
  logoBottom = 20,
  logoRight = 20,
  logoScale = 1,
  logoOpacity = 0.9,
  blurAmount = 20,
  logoBackgroundTransparency = 0.55,
  previewMode = false,
}) => {
  const logoOverlay = (
    <div
      style={{
        position: "absolute",
        bottom: logoBottom,
        right: logoRight,
        background: previewMode
          ? `rgba(20, 20, 20, 0.9)`
          : `rgba(0, 0, 0, ${1 - logoBackgroundTransparency})`,
        backdropFilter: previewMode ? "none" : `blur(${blurAmount}px)`,
        height: 90 * logoScale,
        padding: "10px 16px",
        borderRadius: "16px",
        display: "flex",
        justifyContent: "center",
        alignItems: "center",
      }}
    >
      <Img
        src={logoImg}
        style={{ height: "100%", objectFit: "contain", opacity: logoOpacity }}
      />
    </div>
  );

  return (
    <AbsoluteFill style={{ backgroundColor: "black" }}>
      <Series>
        {/* Intro */}
        <Series.Sequence durationInFrames={300}>
          <Video
            src={introVideo}
            style={{ width: "100%", height: "100%", objectFit: "cover" }}
            onError={(e) => console.log("Video decode error ignored", e)}
          />
          {logoOverlay}
        </Series.Sequence>

        {/* Main Content */}
        <Series.Sequence durationInFrames={videoData.totalFrames}>
          <MainContent previewMode={previewMode} logoOverlay={logoOverlay} />
        </Series.Sequence>

        {/* Outro */}
        <Series.Sequence durationInFrames={300}>
          <Video
            src={outroVideo}
            style={{ width: "100%", height: "100%", objectFit: "cover" }}
            onError={(e) => console.log("Video decode error ignored", e)}
          />
          {logoOverlay}
        </Series.Sequence>
      </Series>
    </AbsoluteFill>
  );
};
